import type { BotCatalogEntry } from "./types";

export const BOT_CATALOG: readonly BotCatalogEntry[] = [
  { token: "GPTBot", botId: "gptbot", botName: "GPTBot", vendor: "OpenAI", purpose: "training" },
  { token: "OAI-SearchBot", botId: "oai-searchbot", botName: "OAI-SearchBot", vendor: "OpenAI", purpose: "search_indexing" },
  { token: "ChatGPT-User", botId: "chatgpt-user", botName: "ChatGPT-User", vendor: "OpenAI", purpose: "realtime_citation" },
  { token: "OAI-AdsBot", botId: "oai-adsbot", botName: "OAI-AdsBot", vendor: "OpenAI", purpose: "other" },
  { token: "ClaudeBot", botId: "claudebot", botName: "ClaudeBot", vendor: "Anthropic", purpose: "training" },
  { token: "Claude-SearchBot", botId: "claude-searchbot", botName: "Claude-SearchBot", vendor: "Anthropic", purpose: "search_indexing" },
  { token: "Claude-User", botId: "claude-user", botName: "Claude-User", vendor: "Anthropic", purpose: "realtime_citation" },
  { token: "Claude-Web", botId: "claude-web", botName: "Claude-Web", vendor: "Anthropic", purpose: "realtime_citation" },
  { token: "anthropic-ai", botId: "anthropic-ai", botName: "anthropic-ai", vendor: "Anthropic", purpose: "training" },
  { token: "PerplexityBot", botId: "perplexitybot", botName: "PerplexityBot", vendor: "Perplexity", purpose: "search_indexing" },
  { token: "Perplexity-User", botId: "perplexity-user", botName: "Perplexity-User", vendor: "Perplexity", purpose: "realtime_citation" },
  { token: "Googlebot", botId: "googlebot", botName: "Googlebot", vendor: "Google", purpose: "search_indexing" },
  { token: "Googlebot-Image", botId: "googlebot-image", botName: "Googlebot-Image", vendor: "Google", purpose: "search_indexing" },
  { token: "Googlebot-Video", botId: "googlebot-video", botName: "Googlebot-Video", vendor: "Google", purpose: "search_indexing" },
  { token: "GoogleOther", botId: "googleother", botName: "GoogleOther", vendor: "Google", purpose: "search_indexing" },
  { token: "GoogleOther-Image", botId: "googleother-image", botName: "GoogleOther-Image", vendor: "Google", purpose: "search_indexing" },
  { token: "GoogleOther-Video", botId: "googleother-video", botName: "GoogleOther-Video", vendor: "Google", purpose: "search_indexing" },
  { token: "Google-Extended", botId: "google-extended", botName: "Google-Extended", vendor: "Google", purpose: "training" },
  { token: "Yeti", botId: "yeti", botName: "Yeti", vendor: "Naver", purpose: "search_indexing" },
  { token: "NaverBot", botId: "naverbot", botName: "NaverBot", vendor: "Naver", purpose: "search_indexing" },
  { token: "bingbot", botId: "bingbot", botName: "bingbot", vendor: "Microsoft", purpose: "search_indexing" },
  { token: "msnbot", botId: "msnbot", botName: "msnbot", vendor: "Microsoft", purpose: "search_indexing" },
  { token: "BingPreview", botId: "bingpreview", botName: "BingPreview", vendor: "Microsoft", purpose: "search_indexing" },
  { token: "MicrosoftPreview", botId: "microsoftpreview", botName: "MicrosoftPreview", vendor: "Microsoft", purpose: "search_indexing" },
  { token: "Applebot", botId: "applebot", botName: "Applebot", vendor: "Apple", purpose: "search_indexing" },
  { token: "Applebot-Extended", botId: "applebot-extended", botName: "Applebot-Extended", vendor: "Apple", purpose: "training" },
  { token: "DuckAssistBot", botId: "duckassistbot", botName: "DuckAssistBot", vendor: "DuckDuckGo", purpose: "realtime_citation" },
  { token: "DuckDuckBot", botId: "duckduckbot", botName: "DuckDuckBot", vendor: "DuckDuckGo", purpose: "search_indexing" },
  { token: "Amazonbot", botId: "amazonbot", botName: "Amazonbot", vendor: "Amazon", purpose: "training" },
  { token: "Amzn-SearchBot", botId: "amzn-searchbot", botName: "Amzn-SearchBot", vendor: "Amazon", purpose: "search_indexing" },
  { token: "Amzn-User", botId: "amzn-user", botName: "Amzn-User", vendor: "Amazon", purpose: "realtime_citation" },
  { token: "Meta-WebIndexer", botId: "meta-webindexer", botName: "Meta-WebIndexer", vendor: "Meta", purpose: "search_indexing" },
  { token: "Meta-ExternalFetcher", botId: "meta-externalfetcher", botName: "Meta-ExternalFetcher", vendor: "Meta", purpose: "realtime_citation" },
  { token: "Meta-ExternalAgent", botId: "meta-externalagent", botName: "Meta-ExternalAgent", vendor: "Meta", purpose: "training" },
  { token: "Meta-ExternalAds", botId: "meta-externalads", botName: "Meta-ExternalAds", vendor: "Meta", purpose: "other" },
  { token: "FacebookExternalHit", botId: "facebookexternalhit", botName: "FacebookExternalHit", vendor: "Meta", purpose: "other" },
  { token: "CCBot", botId: "ccbot", botName: "CCBot", vendor: "Common Crawl", purpose: "training" },
  { token: "Bytespider", botId: "bytespider", botName: "Bytespider", vendor: "ByteDance", purpose: "training" },
  { token: "YouBot", botId: "youbot", botName: "YouBot", vendor: "You.com", purpose: "search_indexing" },
  { token: "cohere-ai", botId: "cohere-ai", botName: "cohere-ai", vendor: "Cohere", purpose: "training" },
  { token: "MistralAI-User", botId: "mistralai-user", botName: "MistralAI-User", vendor: "Mistral AI", purpose: "realtime_citation" },
];
